# name: Workflow Eventos com workflow_dispatch
# on:
#     workflow_dispatch:
        
# jobs:
#     teste:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Action de teste
#               run: echo "Disparando o evento"

#########################################################################################################


name: Workflow Eventos com Push
on:
    push:
        branches: ["main", "feature/*"] #Workflow será executado somente se o push for realizado na
jobs:                                      #branche "main" e/ou na "feature/*"
    teste:
        runs-on: ubuntu-latest
        steps:
            - name: Action de teste
              run: echo "Action executada apenas na branches Main e Feature"

#OBS.: O evento será disparado somente na Branche corrente, não afetando as outras Branches mesmo que esteja no mesmo Workflow

#########################################################################################################


