name: Workflow Eventos
on:
    workflow_dispatch:
        
jobs:
    teste:
        runs-on: ubuntu-latest
        steps:
            - name: Action de teste
              run: echo "Disparando o evento"

