# name: Workflow Eventos com workflow_dispatch
# on:
#     workflow_dispatch:
        
# jobs:
#     teste:
#         runs-on: ubuntu-latest
#         steps:
#             - name: Action de teste
#               run: echo "Disparando o evento"

#########################################################################################################


name: Workflow Eventos com Push
on:
    push:
        branches: ["main", "feature/*"] #Workflow será executado somente se o push for realizado na branche "main" e/ou na "feature/*"
        paths:      #Pipeline só irá disparar se houver alteração em algum arquivo no diretório SRC
            - "src/**"
        tags:           #Evento será ativado quando o Push tiver marcado com uma Tag "V". Ex: v1.0.0
            - v*
jobs:                                     
    teste:
        runs-on: ubuntu-latest
        steps:
            - name: Action de teste
              run: echo "Action executada apenas na branches Main e Feature"

#OBS.: O evento será disparado somente na Branche corrente, não afetando as outras Branches mesmo que esteja no mesmo Workflow

#########################################################################################################


